version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-3.3.15
    container_name: censoratogenerale_db
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atom
      MYSQL_USER: atom
      MYSQL_PASSWORD: password
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
#    image: php:7.0-fpm-alpine
    image: wodby/php:7.1-dev-4.11.8
    container_name: censoratogenerale_php
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: atom
      DB_PASSWORD: password
      DB_NAME: atom
#      PHP_FPM_USER: wodby
#      PHP_FPM_GROUP: wodby
    volumes:
      - ./web:/var/www/html/censoratogenerale

  nginx:
    image: wodby/nginx:1.15-5.3.9
    container_name: censoratogenerale_nginx
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: php
      NGINX_SERVER_ROOT: /var/www/html/
    volumes:
      - ./docroot:/var/www/html
      - ./web:/var/www/html/censoratogenerale
    ports:
      - "9000:80"

  mailhog:
    image: mailhog/mailhog
    container_name: censoratogenerale_mailhog

#  elasticsearch:
#    image: wodby/elasticsearch:6.7-4.1.2
#    container_name: censoratogenerale_elasticsearch
#    environment:
#      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    ports:
#      - "7000:9200"
#    volumes:
#      - ./elasticsearch_data:/usr/share/elasticsearch/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    container_name: censoratogenerale_elasticsearch
    environment:
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms640m -Xmx640m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "63002:9200"
    expose:
      - "9300"
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
