<?php
// auto-generated by sfInstall::configureDatabase()
// date: 2019/04/18 13:41:00

return array (
  'all' => 
  array (
    'propel' => 
    array (
      'class' => 'sfPropelDatabase',
      'param' => 
      array (
        'encoding' => 'utf8',
        'persistent' => true,
        'pooling' => true,
        'dsn' => 'mysql:dbname=atom;host=mariadb;port=3306',
        'username' => 'atom',
        'password' => 'password',
      ),
    ),
  ),
  'dev' => 
  array (
    'propel' => 
    array (
      'param' => 
      array (
        'classname' => 'DebugPDO',
        'debug' => 
        array (
          'realmemoryusage' => true,
          'details' => 
          array (
            'time' => 
            array (
              'enabled' => true,
            ),
            'slow' => 
            array (
              'enabled' => true,
              'threshold' => 0.1,
            ),
            'mem' => 
            array (
              'enabled' => true,
            ),
            'mempeak' => 
            array (
              'enabled' => true,
            ),
            'memdelta' => 
            array (
              'enabled' => true,
            ),
          ),
        ),
      ),
    ),
  ),
  'test' => 
  array (
    'propel' => 
    array (
      'param' => 
      array (
        'classname' => 'DebugPDO',
      ),
    ),
  ),
);
