<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/04/18 20:40:48
sfConfig::add(array(
  'app_upload_limit' => -1.0,
  'app_download_timeout' => 10,
  'app_cache_engine' => 'sfAPCCache',
  'app_read_only' => false,
  'app_htmlpurifier_enabled' => false,
));
