<?php
// auto-generated by sfCacheConfigHandler
// date: 2019/04/18 13:40:48
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

