<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/04/18 13:40:46
sfConfig::add(array(
  'mod_sfinstallplugin_enabled' => true,
  'mod_sfinstallplugin_view_class' => 'sfPHP',
));
