<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/04/18 13:40:46
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 'administrator',
  ),
);
